const StudentFormEnum = {
    EMPTY: 'EMPTY',
    UPDATE: 'UPDATE',
    SUBMIT: 'SUBMIT',
    SUBMITONCLICK: 'SUBMITONCLICK',
    SUBMITCONFIRMED: 'SUBMITCONFIRMED',
    SUBMITCANCELLED: 'SUBMITCANCELLED',
    REVERT: 'REVERT',
    REVERTONCLICK: 'REVERTONCLICK',
    REVERTCONFIRMED: 'REVERTCONFIRMED',
    REVERTCANCELLED: 'REVERTCANCELLED',
}

export default StudentFormEnum;