const StudentsTableActionEnum = {
    SHOWADDFORM: 'SHOWADDFORM',
    HIDEADDFORM: 'HIDEADDFORM',
    SHOWEDITFORM: 'SHOWEDITFORM',
    HIDEEDITFORM: 'HIDEEDITFORM',
    DELETECONFIRMPROMPT: 'DELETE CONFIRMPROMPT',
    DELETECONFIRMED: 'DELETE CONFIRMED',
    DELETECANCELLED: 'DELETE CANCELLED',
    ADDBACKCONFIRMPROMPT: 'ADD BACK CONFIRMPROMPT',
    ADDBACKCONFIRMED: 'ADD BACK CONFIRMED',
    ADDBACKCANCELLED: 'ADD BACK CANCELLED',
    UPDATECONFIRMPROMPT: 'UPDATE CONFIRMPROMPT',
    UPDATECONFIRMED: 'UPDATE CONFIRMED',
    UPDATECANCELLED: 'UPDATE CANCELLED',
    LOADED: 'LOADED',
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    DELETED: 'DELETED',
    ADDEDBACK: 'ADDEDBACK',
    UPDATE: 'PUT',
    POST: 'POST',
}

export default StudentsTableActionEnum;