const StudentsTableActionEnum = {
    SHOWADDFORM: 'SHOWADDFORM',
    HIDEADDFORM: 'HIDEADDFORM',
    CONFIRMPROMPT: 'CONFIRMPROMPT',
    CONFIRMED: 'CONFIRMED',
    CANCELLED: 'CANCELLED',
    LOADED: 'LOADED',
    LOADING: 'LOADING',
    ERROR: 'ERROR',
    DELETE: 'DELETE',
    UPDATE: 'PUT',
    POST: 'POST',
}

export default StudentsTableActionEnum;